name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        # In order to fetch all tags
        fetch-depth: 0
    - name: Run the build script
      uses: cake-build/cake-action@v1
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      with:
        target: GithubAction
